# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  url = "/authors/admin/"
  weight = 15

[[main]]
  name = "Writing"
  url = "/writing/"
  weight = 20

[[main]]
  name = "Audio"
  url = "/audio/"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40